# Generated by Django 4.0.4 on 2022-05-10 22:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note', models.TextField()),
                ('key', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
                ('self_d', models.DurationField()),
                ('note_name', models.CharField(max_length=100)),
                ('is_d', models.BooleanField(default=False)),
                ('note_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
    ]
