# Generated by Django 4.0.4 on 2022-05-13 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.CharField(default=uuid.UUID('a197ec2d-1d3c-4438-ac46-aa5e62ea0c62'), max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('note', models.TextField()),
                ('key', models.CharField(blank=True, max_length=250)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('self_d', models.DateField(blank=True, null=True)),
                ('note_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_d', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
