# Generated by Django 4.0.4 on 2022-05-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_id',
            field=models.UUIDField(default='14a24968', primary_key=True, serialize=False),
        ),
    ]
