# Generated by Django 4.0.4 on 2022-05-13 17:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('heroo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='key',
        ),
        migrations.AlterField(
            model_name='note',
            name='note_id',
            field=models.CharField(default=uuid.UUID('29f5e8d0-a324-45dc-b0df-03d10b18890b'), max_length=200),
        ),
    ]
