# Generated by Django 4.0.4 on 2022-05-13 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='name',
        ),
    ]
