# Generated by Django 4.0.4 on 2022-05-10 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroo', '0002_alter_note_note_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_id',
            field=models.UUIDField(default='de16c52f', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='self_d',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
