# Generated by Django 4.0.4 on 2022-05-10 22:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('heroo', '0003_alter_note_note_id_alter_note_self_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_id',
            field=models.UUIDField(default=uuid.UUID('912c7465-cd7b-4fca-8af9-89dedfac205a'), primary_key=True, serialize=False),
        ),
    ]
