# Generated by Django 4.0.4 on 2022-05-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroo', '0003_alter_note_self_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='self_d',
            field=models.DateField(blank=True, null=True),
        ),
    ]
