# Generated by Django 4.0.4 on 2022-05-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroo', '0006_alter_note_date_alter_note_self_d'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date',
            new_name='date_c',
        ),
    ]
