# Generated by Django 3.2.13 on 2022-05-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroo', '0008_alter_note_date_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_c',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
