# Generated by Django 3.2.13 on 2022-05-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroo', '0010_alter_note_self_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_c',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
